@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 05 02:07:34 -0400 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Control_TB_behav -key {Behavioral:Control_Test:Functional:Control_TB} -tclbatch Control_TB.tcl -view C:/Users/hpcpe/Documents/GitHub/HB_426_Lab4/TEST1/Control_TB_behav.wcfg -log simulate.log"
call xsim  Control_TB_behav -key {Behavioral:Control_Test:Functional:Control_TB} -tclbatch Control_TB.tcl -view C:/Users/hpcpe/Documents/GitHub/HB_426_Lab4/TEST1/Control_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
